[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"